export const ADMIN_DELIVERIES_REQUEST = 'ADMIN_DELIVERIES_REQUEST'
export const ADMIN_DELIVERIES_SUCCESS = 'ADMIN_DELIVERIES_SUCCESS'
export const ADMIN_DELIVERIES_FAIL = 'ADMIN_DELIVERIES_FAIL'

export const NEW_DELIVERY_REQUEST = 'NEW_DELIVERY_REQUEST'
export const NEW_DELIVERY_SUCCESS = 'NEW_DELIVERY_SUCCESS'
export const NEW_DELIVERY_RESET = 'NEW_DELIVERY_RESET'
export const NEW_DELIVERY_FAIL = 'NEW_DELIVERY_FAIL'

export const DELETE_DELIVERY_REQUEST = 'DELETE_DELIVERY_REQUEST'
export const DELETE_DELIVERY_SUCCESS = 'DELETE_DELIVERY_SUCCESS'
export const DELETE_DELIVERY_RESET = 'DELETE_DELIVERY_RESET'
export const DELETE_DELIVERY_FAIL = 'DELETE_DELIVERY_FAIL'

export const UPDATE_DELIVERY_REQUEST = 'UPDATE_DELIVERY_REQUEST'
export const UPDATE_DELIVERY_SUCCESS = 'UPDATE_DELIVERY_SUCCESS'
export const UPDATE_DELIVERY_RESET = 'UPDATE_DELIVERY_RESET'
export const UPDATE_DELIVERY_FAIL = 'UPDATE_DELIVERY_FAIL'

export const DELIVERY_DETAILS_REQUEST = 'DELIVERY_DETAILS_REQUEST'
export const DELIVERY_DETAILS_SUCCESS = 'DELIVERY_DETAILS_SUCCESS'
export const DELIVERY_DETAILS_FAIL = 'DELIVERY_DETAILS_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'